theme: jekyll-theme-minimal
logo: "https://media.discordapp.net/attachments/855806170966261791/875947180005949481/lel.png"
description: "The Github Pro Documentation Page"
title: "Documentation"
show_downloads: true
show_binares: true
url: "https://kadedevteam.github.io/Documentations/"
